"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MenuSection = exports.Menu = exports.SystemConfig = exports.Notification = exports.Payment = exports.Category = exports.User = exports.Room = exports.Order = exports.Dish = void 0;
var Dish_1 = require("./Dish");
Object.defineProperty(exports, "Dish", { enumerable: true, get: function () { return __importDefault(Dish_1).default; } });
var Order_1 = require("./Order");
Object.defineProperty(exports, "Order", { enumerable: true, get: function () { return __importDefault(Order_1).default; } });
var Room_1 = require("./Room");
Object.defineProperty(exports, "Room", { enumerable: true, get: function () { return __importDefault(Room_1).default; } });
var User_1 = require("./User");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return __importDefault(User_1).default; } });
var Category_1 = require("./Category");
Object.defineProperty(exports, "Category", { enumerable: true, get: function () { return __importDefault(Category_1).default; } });
var Payment_1 = require("./Payment");
Object.defineProperty(exports, "Payment", { enumerable: true, get: function () { return __importDefault(Payment_1).default; } });
var Notification_1 = require("./Notification");
Object.defineProperty(exports, "Notification", { enumerable: true, get: function () { return __importDefault(Notification_1).default; } });
var SystemConfig_1 = require("./SystemConfig");
Object.defineProperty(exports, "SystemConfig", { enumerable: true, get: function () { return __importDefault(SystemConfig_1).default; } });
var Menu_1 = require("./Menu");
Object.defineProperty(exports, "Menu", { enumerable: true, get: function () { return Menu_1.Menu; } });
Object.defineProperty(exports, "MenuSection", { enumerable: true, get: function () { return Menu_1.MenuSection; } });
